// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.15.8
// source: manifest.proto

package mevmanifest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Manifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Files         []*File                `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	Bundles       []*Bundle              `protobuf:"bytes,3,rep,name=bundles,proto3" json:"bundles,omitempty"`
	Rebase        string                 `protobuf:"bytes,4,opt,name=rebase,proto3" json:"rebase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_manifest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_manifest_proto_rawDescGZIP(), []int{0}
}

func (x *Manifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Manifest) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Manifest) GetBundles() []*Bundle {
	if x != nil {
		return x.Bundles
	}
	return nil
}

func (x *Manifest) GetRebase() string {
	if x != nil {
		return x.Rebase
	}
	return ""
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Checksum      string                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	DownloadPath  string                 `protobuf:"bytes,5,opt,name=download_path,json=downloadPath,proto3" json:"download_path,omitempty"`
	Patches       []*PatchFile           `protobuf:"bytes,6,rep,name=patches,proto3" json:"patches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_manifest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_manifest_proto_rawDescGZIP(), []int{1}
}

func (x *File) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *File) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *File) GetDownloadPath() string {
	if x != nil {
		return x.DownloadPath
	}
	return ""
}

func (x *File) GetPatches() []*PatchFile {
	if x != nil {
		return x.Patches
	}
	return nil
}

type PatchFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Checksum      string                 `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	DownloadPath  string                 `protobuf:"bytes,4,opt,name=download_path,json=downloadPath,proto3" json:"download_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchFile) Reset() {
	*x = PatchFile{}
	mi := &file_manifest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchFile) ProtoMessage() {}

func (x *PatchFile) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchFile.ProtoReflect.Descriptor instead.
func (*PatchFile) Descriptor() ([]byte, []int) {
	return file_manifest_proto_rawDescGZIP(), []int{2}
}

func (x *PatchFile) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PatchFile) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *PatchFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PatchFile) GetDownloadPath() string {
	if x != nil {
		return x.DownloadPath
	}
	return ""
}

type Bundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	DownloadPath  string                 `protobuf:"bytes,2,opt,name=download_path,json=downloadPath,proto3" json:"download_path,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Checksum      string                 `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bundle) Reset() {
	*x = Bundle{}
	mi := &file_manifest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bundle) ProtoMessage() {}

func (x *Bundle) ProtoReflect() protoreflect.Message {
	mi := &file_manifest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bundle.ProtoReflect.Descriptor instead.
func (*Bundle) Descriptor() ([]byte, []int) {
	return file_manifest_proto_rawDescGZIP(), []int{3}
}

func (x *Bundle) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Bundle) GetDownloadPath() string {
	if x != nil {
		return x.DownloadPath
	}
	return ""
}

func (x *Bundle) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Bundle) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

var File_manifest_proto protoreflect.FileDescriptor

const file_manifest_proto_rawDesc = "" +
	"\n" +
	"\x0emanifest.proto\x12\bmanifest\"\x8e\x01\n" +
	"\bManifest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12$\n" +
	"\x05files\x18\x02 \x03(\v2\x0e.manifest.FileR\x05files\x12*\n" +
	"\abundles\x18\x03 \x03(\v2\x10.manifest.BundleR\abundles\x12\x16\n" +
	"\x06rebase\x18\x04 \x01(\tR\x06rebase\"\xae\x01\n" +
	"\x04File\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\tR\bchecksum\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12#\n" +
	"\rdownload_path\x18\x05 \x01(\tR\fdownloadPath\x12-\n" +
	"\apatches\x18\x06 \x03(\v2\x13.manifest.PatchFileR\apatches\"z\n" +
	"\tPatchFile\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\tR\bchecksum\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12#\n" +
	"\rdownload_path\x18\x04 \x01(\tR\fdownloadPath\"w\n" +
	"\x06Bundle\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12#\n" +
	"\rdownload_path\x18\x02 \x01(\tR\fdownloadPath\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksumB>Z<github.com/justjack1521/mevmanifest/pkg/genproto/mevmanifestb\x06proto3"

var (
	file_manifest_proto_rawDescOnce sync.Once
	file_manifest_proto_rawDescData []byte
)

func file_manifest_proto_rawDescGZIP() []byte {
	file_manifest_proto_rawDescOnce.Do(func() {
		file_manifest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manifest_proto_rawDesc), len(file_manifest_proto_rawDesc)))
	})
	return file_manifest_proto_rawDescData
}

var file_manifest_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_manifest_proto_goTypes = []any{
	(*Manifest)(nil),  // 0: manifest.Manifest
	(*File)(nil),      // 1: manifest.File
	(*PatchFile)(nil), // 2: manifest.PatchFile
	(*Bundle)(nil),    // 3: manifest.Bundle
}
var file_manifest_proto_depIdxs = []int32{
	1, // 0: manifest.Manifest.files:type_name -> manifest.File
	3, // 1: manifest.Manifest.bundles:type_name -> manifest.Bundle
	2, // 2: manifest.File.patches:type_name -> manifest.PatchFile
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_manifest_proto_init() }
func file_manifest_proto_init() {
	if File_manifest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manifest_proto_rawDesc), len(file_manifest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_manifest_proto_goTypes,
		DependencyIndexes: file_manifest_proto_depIdxs,
		MessageInfos:      file_manifest_proto_msgTypes,
	}.Build()
	File_manifest_proto = out.File
	file_manifest_proto_goTypes = nil
	file_manifest_proto_depIdxs = nil
}
