// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package mevmanifest

type ApplicationFile struct {
	Path        string
	Size        int64
	Checksum    string
	Timestamp   int64
	Application string
}

type ApplicationVersion struct {
	Name  string
	Major int64
	Minor int64
	Patch int64
}
