// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package mevmanifest

import (
	"context"
)

const getApplicationFiles = `-- name: GetApplicationFiles :many
SELECT path, size, timestamp, application FROM ApplicationFile
WHERE Application = ?
`

func (q *Queries) GetApplicationFiles(ctx context.Context, application string) ([]ApplicationFile, error) {
	rows, err := q.db.QueryContext(ctx, getApplicationFiles, application)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationFile
	for rows.Next() {
		var i ApplicationFile
		if err := rows.Scan(
			&i.Path,
			&i.Size,
			&i.Timestamp,
			&i.Application,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationVersion = `-- name: GetApplicationVersion :one
SELECT name, major, minor, patch FROM ApplicationVersion
WHERE Name = ? LIMIT 1
`

func (q *Queries) GetApplicationVersion(ctx context.Context, name string) (ApplicationVersion, error) {
	row := q.db.QueryRowContext(ctx, getApplicationVersion, name)
	var i ApplicationVersion
	err := row.Scan(
		&i.Name,
		&i.Major,
		&i.Minor,
		&i.Patch,
	)
	return i, err
}
